### ISSUE TITLE
Suporte a NotificationUrl

### ISSUE THREAD

**Issue by fdc263** [mundipagg/mundipagg-one-ruby#12]
Me parece que a gem ainda não dá suporte ao envio da url de notificação do boleto.

http://docs.mundipagg.com/docs/posts-de-notifica%C3%A7%C3%A3o#section-enviando-a-url-na-requisição

Podem disponibilizar?

**Comment by munirwanis** [comment]
Aceitei o seu PR, vou lançar uma nova versão
