### ISSUE TITLE
Rubygem desatualizado

### ISSUE THREAD

**Issue by adrianoresende** [mundipagg/mundipagg-one-ruby#4]
Por favor atualizem no RubyGem que a versão é antiga, devido desse problema eu demorei horas pra achar o erro.

**Comment by munirwanis** [comment]
Foi enviado um email para os clientes informando que ela será atualizada no dia 27 de fevereiro para evitar que quebre os clientes devido ao acréscimo do `Module::Gateway` em todas as funções. Você pode atualizar manualmente sua gem baixando a última versão no link: https://github.com/mundipagg/mundipagg-one-ruby/releases

**Comment by adrianoresende** [comment]
Ah sim, muito obrigado!
