### ISSUE TITLE
Namespace utilizando nomenclatura genérica

### ISSUE THREAD

**Issue by hugodemiglio** [mundipagg/mundipagg-one-ruby#6]
Olá,

Utilizo em minha aplicação uma classe cujo nome já utiliza a constante `Gateway`. Vocês utilizaram este mesmo nome para o namespace do novo SDK. Acredito que seja um nome muito genérico e que isso pode causar problemas de compatibilidade com demais plataformas e bibliotecas. Vários sistemas que utilizam métodos de pagamentos tem classes chamadas `Gateway` onde nela os demais gateways são gerenciados. Como sugestão, o namespace de vocês deveria ser algo mais especifico como `MundiPaggSDK` ou algo assim. Usar `Gateway` como nome seria a mesma coisa que o Facebook lançar um SDK com o namespace `SocialNetwork`, que alem de genérico e não referir ao que se trata, pode causar problemas de compatibilidade nas plataformas.

Desde já agradeço,
Hugo Demiglio.

**Comment by munirwanis** [comment]
Olá,
Você pode usar um alias para o `module`.

http://stackoverflow.com/questions/11091740/is-it-possible-to-make-an-alias-for-a-module-in-ruby

```ruby
[4] (pry) main: 0> module TestModule
[4] (pry) main: 0*   def self.foo
[4] (pry) main: 0*     "test"
[4] (pry) main: 0*   end  
[4] (pry) main: 0* end  
=> nil
[5] (pry) main: 0> tm = TestModule
=> TestModule
[6] (pry) main: 0> tm.foo
=> "test"
```

**Comment by hugodemiglio** [comment]
Olá Munir,

Obrigado pela resposta, sei que existem métodos para contornar isso. Não sei se você faz parte do dev-team, mas um nome genérico assim pode gerar colisão com constantes de vários sistemas, `Gateway` é um nome comum. Imagina se outros gateways de pagamento fizessem isso e colocassem todos como Gateway, seria um grande problema. Cada um tem que ter seu nome.

Mais uma vez obrigado pela atenção,
Hugo Demiglio.

**Comment by hugodemiglio** [comment]
Olá Munir,

Testei aqui e a solução que me passou não resolve o problema, eu tenho uma classe na minha aplicação que chama Gateway que colidiu com o namespace do SDK de vocês. Não foram dois namespaces e sim uma classe com um namespace.

Eu não posso mudar o nome dessa classe pois ela gerencia a minha interface com os demais gateways, ou seja, o nome é semântico e é estendido por várias classes minhas. Para eu poder utilizar a gem de vocês, teria que fazer literalmente uma gambiarra no loader das gems do Rails ou fazer um fork do repositório alterando todos os módulos do SDK.

Acho erronia a escolha de um nome genérico para o namespace de um SDK.
Como eu ja disse, imagina se todos os gateways tipo a stone, cielo ou qualquer outro, resolver lançar um SDK e também chamar de Gateway, afinal são gateways, não é?

Mais uma vez obrigado pela atenção,
Hugo Demiglio.

**Comment by munirwanis** [comment]
Peço desculpas @hugodemiglio, mas infelizmente não teremos como fazer esta alteração.

**Comment by hugodemiglio** [comment]
Olá @munirwanis,

Olhando a gem da Stone, que acredito que seja da mesma empresa que a MundiPagg, pois você desenvolveu as duas... Percebi que também chamou o namespace de Gateway...

Te convido a testar uma aplicação Rails usando as duas gems. Um simples teste, que não leva mais que cinco minutos. Coloque as duas gems no Gemfile e tente fazer a implementação das duas em uma classe. Vai dar warning e você só vai conseguir usar a ultima que foi carregada no loader do Rails.

A MundiPagg não chama gateway, ela é um gateway. Dar um nome genérico a um pacote é um erro grave, que só vai trazer dor de cabeça para quem for utilizar.

Tenho certeza que não vai demorar muito para mais desenvolvedores criarem issues sobre isso ou abrir chamados técnicos no suporte. Da próxima vez chama o namespace de Gem, afinal é uma gem e tem como fazer gambiarras no loader do bundle para clonar o objeto em uma nova constante, pouco importa a nomenclatura original, não é mesmo?

Nomes são importantes, espero que revejam isso.
Faz pouco tempo que foi lançada essa gem, ainda está em tempo de corrigir.

Abraços.
