### ISSUE TITLE
Informações do comprador

### ISSUE THREAD

**Issue by adrianoresende** [mundipagg/mundipagg-one-ruby#7]
Boa tarde,

Estou tentando preencher o nome e email apenas do comprador mas retorna um erro faltando do campo do documento CPF ou CPNJ (`Buyer.TaxDocumentNumber`), por acaso é possível preencher alguns campos do Buyer sem precisar o número do documento?

Acho desnecessário colocar obrigatório, pois as informações dos clientes ficam no meu sistema da empresa, acho que é suficiente preencher o nome e email ou `BuyerReference` na plataforma do pagamento, não acha?

```ruby
createSaleRequest.Buyer.Email = current_client.email if current_client.email
createSaleRequest.Buyer.Name = current_client.name
createSaleRequest.Buyer.BuyerReference = "#{current_client.name} ##{current_client.id} - URL: #{admin_client_url(current_client.id)}"
```

**Comment by munirwanis** [comment]
Boa tarde, @adrianoresende 
Os itens obrigatórios encontram-se na documentação da [API](http://docs.mundipagg.com/v1.0/docs)
Se você não utilizar anti-fraude não precisará enviar o Buyer.

Quando tiver dúvidas relacionadas a nossa API, por favor entre em contato com o [RC da Mundipagg](https://mundipagg.zendesk.com/hc/pt-br)!
